namespace Web.Common.Extensions;
public class PhoneExtensions
{
    public static string NormalizePhoneNumber(string phone)
    {
        // remove all space in phone number
        return phone.Trim().Trim('-')
            .Trim('(').Trim(')').TrimStart('+').TrimStart('0');
    }

    public static Dictionary<int, List<string>> GetCountryCodeToRegionCodeMap()
        => new Dictionary<int, List<string>>(286)
        {
            { 1, new List<string>
                {
                    "US","AG","AI","AS","BB",
                    "BM","BS","CA","DM","DO",
                    "GD","GU","JM","KN","KY",
                    "LC","MP","MS","PR","SX",
                    "TC","TT","VC","VG","VI"
                }
            },
            { 7, new List<string>{    "RU",    "KZ"}},
            { 20, new List<string> { "EG" }},
            { 27, new List<string> { "ZA" }},
            { 30, new List<string> { "GR" }},
            { 31, new List<string> { "NL" }},
            { 32, new List<string> { "BE" }},
            { 33, new List<string> { "FR" }},
            { 34, new List<string> { "ES" }},
            { 36, new List<string> { "HU" }},
            { 39, new List<string>{"IT","VA"}},
            { 40, new List<string> { "RO" }},
            { 41, new List<string> { "CH" }},
            { 43, new List<string> { "AT" }},
            { 44, new List<string>{"GB","GG","IM","JE"}},
            { 45, new List<string> { "DK" }},
            { 46, new List<string> { "SE" }},
            { 47, new List<string>{"NO","SJ"}},
            { 48, new List<string> { "PL" }},
            { 49, new List<string> { "DE" }},
            { 51, new List<string> { "PE" }},
            { 52, new List<string> { "MX" }},
            { 53, new List<string> { "CU" }},
            { 54, new List<string> { "AR" }},
            { 55, new List<string> { "BR" }},
            { 56, new List<string> { "CL" }},
            { 57, new List<string> { "CO" }},
            { 58, new List<string> { "VE" }},
            { 60, new List<string> { "MY" }},
            { 61, new List<string>{"AU","CC","CX"}},
            { 62, new List<string> { "ID" }},
            { 63, new List<string> { "PH" }},
            { 64, new List<string> { "NZ" }},
            { 65, new List<string> { "SG" }},
            { 66, new List<string> { "TH" }},
            { 81, new List<string> { "JP" }},
            { 82, new List<string> { "KR" }},
            { 84, new List<string> { "VN" }},
            { 86, new List<string> { "CN" }},
            { 90, new List<string> { "TR" }},
            { 91, new List<string> { "IN" }},
            { 92, new List<string> { "PK" }},
            { 93, new List<string> { "AF" }},
            { 94, new List<string> { "LK" }},
            { 95, new List<string> { "MM" }},
            { 98, new List<string> { "IR" }},
            { 211, new List<string> { "SS" }},
            { 212, new List<string>{    "MA",    "EH"}},
            { 213, new List<string> { "DZ" }},
            { 216, new List<string> { "TN" }},
            { 218, new List<string> { "LY" }},
            { 220, new List<string> { "GM" }},
            { 221, new List<string> { "SN" }},
            { 222, new List<string> { "MR" }},
            { 223, new List<string> { "ML" }},
            { 224, new List<string> { "GN" }},
            { 225, new List<string> { "CI" }},
            { 226, new List<string> { "BF" }},
            { 227, new List<string> { "NE" }},
            { 228, new List<string> { "TG" }},
            { 229, new List<string> { "BJ" }},
            { 230, new List<string> { "MU" }},
            { 231, new List<string> { "LR" }},
            { 232, new List<string> { "SL" }},
            { 233, new List<string> { "GH" }},
            { 234, new List<string> { "NG" }},
            { 235, new List<string> { "TD" }},
            { 236, new List<string> { "CF" }},
            { 237, new List<string> { "CM" }},
            { 238, new List<string> { "CV" }},
            { 239, new List<string> { "ST" }},
            { 240, new List<string> { "GQ" }},
            { 241, new List<string> { "GA" }},
            { 242, new List<string> { "CG" }},
            { 243, new List<string> { "CD" }},
            { 244, new List<string> { "AO" }},
            { 245, new List<string> { "GW" }},
            { 246, new List<string> { "IO" }},
            { 247, new List<string> { "AC" }},
            { 248, new List<string> { "SC" }},
            { 249, new List<string> { "SD" }},
            { 250, new List<string> { "RW" }},
            { 251, new List<string> { "ET" }},
            { 252, new List<string> { "SO" }},
            { 253, new List<string> { "DJ" }},
            { 254, new List<string> { "KE" }},
            { 255, new List<string> { "TZ" }},
            { 256, new List<string> { "UG" }},
            { 257, new List<string> { "BI" }},
            { 258, new List<string> { "MZ" }},
            { 260, new List<string> { "ZM" }},
            { 261, new List<string> { "MG" }},
            { 262, new List<string>{    "RE",    "YT"}},
            { 263, new List<string> { "ZW" }},
            { 264, new List<string> { "NA" }},
            { 265, new List<string> { "MW" }},
            { 266, new List<string> { "LS" }},
            { 267, new List<string> { "BW" }},
            { 268, new List<string> { "SZ" }},
            { 269, new List<string> { "KM" }},
            { 290, new List<string>{    "SH",    "TA"}},
            { 291, new List<string> { "ER" }},
            { 297, new List<string> { "AW" }},
            { 298, new List<string> { "FO" }},
            { 299, new List<string> { "GL" }},
            { 350, new List<string> { "GI" }},
            { 351, new List<string> { "PT" }},
            { 352, new List<string> { "LU" }},
            { 353, new List<string> { "IE" }},
            { 354, new List<string> { "IS" }},
            { 355, new List<string> { "AL" }},
            { 356, new List<string> { "MT" }},
            { 357, new List<string> { "CY" }},
            { 358, new List<string>{    "FI",    "AX"}},
            { 359, new List<string> { "BG" }},
            { 370, new List<string> { "LT" }},
            { 371, new List<string> { "LV" }},
            { 372, new List<string> { "EE" }},
            { 373, new List<string> { "MD" }},
            { 374, new List<string> { "AM" }},
            { 375, new List<string> { "BY" }},
            { 376, new List<string> { "AD" }},
            { 377, new List<string> { "MC" }},
            { 378, new List<string> { "SM" }},
            { 380, new List<string> { "UA" }},
            { 381, new List<string> { "RS" }},
            { 382, new List<string> { "ME" }},
            { 383, new List<string> { "XK" }},
            { 385, new List<string> { "HR" }},
            { 386, new List<string> { "SI" }},
            { 387, new List<string> { "BA" }},
            { 389, new List<string> { "MK" }},
            { 420, new List<string> { "CZ" }},
            { 421, new List<string> { "SK" }},
            { 423, new List<string> { "LI" }},
            { 500, new List<string> { "FK" }},
            { 501, new List<string> { "BZ" }},
            { 502, new List<string> { "GT" }},
            { 503, new List<string> { "SV" }},
            { 504, new List<string> { "HN" }},
            { 505, new List<string> { "NI" }},
            { 506, new List<string> { "CR" }},
            { 507, new List<string> { "PA" }},
            { 508, new List<string> { "PM" }},
            { 509, new List<string> { "HT" }},
            { 590, new List<string>{    "GP",    "BL",    "MF"}},
            { 591, new List<string> { "BO" }},
            { 592, new List<string> { "GY" }},
            { 593, new List<string> { "EC" }},
            { 594, new List<string> { "GF" }},
            { 595, new List<string> { "PY" }},
            { 596, new List<string> { "MQ" }},
            { 597, new List<string> { "SR" }},
            { 598, new List<string> { "UY" }},
            { 599, new List<string>{    "CW",    "BQ"}},
            { 670, new List<string> { "TL" }},
            { 672, new List<string> { "NF" }},
            { 673, new List<string> { "BN" }},
            { 674, new List<string> { "NR" }},
            { 675, new List<string> { "PG" }},
            { 676, new List<string> { "TO" }},
            { 677, new List<string> { "SB" }},
            { 678, new List<string> { "VU" }},
            { 679, new List<string> { "FJ" }},
            { 680, new List<string> { "PW" }},
            { 681, new List<string> { "WF" }},
            { 682, new List<string> { "CK" }},
            { 683, new List<string> { "NU" }},
            { 685, new List<string> { "WS" }},
            { 686, new List<string> { "KI" }},
            { 687, new List<string> { "NC" }},
            { 688, new List<string> { "TV" }},
            { 689, new List<string> { "PF" }},
            { 690, new List<string> { "TK" }},
            { 691, new List<string> { "FM" }},
            { 692, new List<string> { "MH" }},
            { 800, new List<string> { "001" }},
            { 808, new List<string> { "001" }},
            { 850, new List<string> { "KP" }},
            { 852, new List<string> { "HK" }},
            { 853, new List<string> { "MO" }},
            { 855, new List<string> { "KH" }},
            { 856, new List<string> { "LA" }},
            { 870, new List<string> { "001" }},
            { 878, new List<string> { "001" }},
            { 880, new List<string> { "BD" }},
            { 881, new List<string> { "001" }},
            { 882, new List<string> { "001" }},
            { 883, new List<string> { "001" }},
            { 886, new List<string> { "TW" }},
            { 888, new List<string> { "001" }},
            { 960, new List<string> { "MV" }},
            { 961, new List<string> { "LB" }},
            { 962, new List<string> { "JO" }},
            { 963, new List<string> { "SY" }},
            { 964, new List<string> { "IQ" }},
            { 965, new List<string> { "KW" }},
            { 966, new List<string> { "SA" }},
            { 967, new List<string> { "YE" }},
            { 968, new List<string> { "OM" }},
            { 970, new List<string> { "PS" }},
            { 971, new List<string> { "AE" }},
            { 972, new List<string> { "IL" }},
            { 973, new List<string> { "BH" }},
            { 974, new List<string> { "QA" }},
            { 975, new List<string> { "BT" }},
            { 976, new List<string> { "MN" }},
            { 977, new List<string> { "NP" }},
            { 979, new List<string> { "001" }},
            { 992, new List<string> { "TJ" }},
            { 993, new List<string> { "TM" }},
            { 994, new List<string> { "AZ" }},
            { 995, new List<string> { "GE" }},
            { 996, new List<string> { "KG" }},
            { 998, new List<string> { "UZ" }}
        };

}
